# Site settings
title: Dev-E-Loper
email: ""
description: > # this means to ignore newlines until "baseurl:"
  This is text about stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dev-e-loper.github.io" # the base hostname & protocol for your site

plugins: []
paginate: 10
paginate_path: "page:num"

# Build settings
markdown: kramdown
